Test Get EC2 Public IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -69,13 +69,17 @@ jobs:
       - name: Terraform Apply
         run: terraform apply -auto-approve -var="docker_image=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest"
 
-      # 11. Obtener Dirección Pública del EC2
-      - name: Get EC2 Public IP
-        id: get_ec2_ip
-        run: |
-          EC2_PUBLIC_IP=$(terraform output -raw web_server_public_ip | tr -d '\r')
-          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP"
-          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
+    # 11. Obtener Dirección Pública del EC2
+    - name: Get EC2 Public IP
+      id: get_ec2_ip
+      run: |
+        EC2_PUBLIC_IP=$(/home/runner/work/_temp/27d2988d-b295-4c91-a9bf-f9020455c31f/terraform-bin output -raw web_server_public_ip 2>/dev/null | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+        if [ -z "$EC2_PUBLIC_IP" ]; then
+          echo "Error: EC2_PUBLIC_IP is empty. Check your Terraform outputs."
+          exit 1
+        fi
+        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP"
+        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
 
       # 12. Configurar EC2 y Desplegar el Contenedor
       - name: Configure EC2 and Deploy Container
