Test Get EC2 Public IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -78,18 +78,23 @@ jobs:
       # 12. Obtener Dirección Pública del EC2
       # - name: Debug EC2 Public IP
       #   run: echo "Extracted EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
-        
-      - name: Get EC2 Public IP
-        id: get_ec2_ip
+
+      - name: Save EC2 IP to File
         run: |
           RAW_OUTPUT=$(terraform output -raw web_server_public_ip || true)
-          EC2_PUBLIC_IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
-          if [ -z "$EC2_PUBLIC_IP" ]; then
-            echo "Error: Could not extract a valid IP address."
-            exit 1
-          fi
-          echo "Extracted EC2 Public IP: $EC2_PUBLIC_IP"
-          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
+          echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' > ec2_ip.txt
+
+      # - name: Get EC2 Public IP
+      #   id: get_ec2_ip
+      #   run: |
+      #     RAW_OUTPUT=$(terraform output -raw web_server_public_ip || true)
+      #     EC2_PUBLIC_IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+      #     if [ -z "$EC2_PUBLIC_IP" ]; then
+      #       echo "Error: Could not extract a valid IP address."
+      #       exit 1
+      #     fi
+      #     echo "Extracted EC2 Public IP: $EC2_PUBLIC_IP"
+      #     echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
 
       # # 13. Depurar Dirección Pública del EC2 Exportada
       # - name: Debug EC2 Public IP
