Test Get EC2 Public IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -72,9 +72,6 @@ jobs:
         run: |
           terraform output -raw web_server_public_ip || true
 
-      - name: Debug GITHUB_ENV
-        run: cat $GITHUB_ENV
-
       # 12. Obtener Dirección Pública del EC2
       # - name: Debug EC2 Public IP
       #   run: echo "Extracted EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
@@ -112,25 +109,31 @@ jobs:
           echo "EC2_PUBLIC_IP=$CLEANED_IP" >> $GITHUB_ENV
           echo "Extracted EC2 Public IP: $CLEANED_IP"
 
-      - name: Read EC2 IP from File
+      # Read EC2 IP
+      - name: Read and Verify EC2 IP
         run: |
-          if [ -f ec2_ip.txt ]; then
-            RAW_IP=$(cat ec2_ip.txt | tr -d '\r\n')
-            EC2_PUBLIC_IP=$(echo "$RAW_IP" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
-            
-            # Validar que la IP es válida
-            if [ -z "$EC2_PUBLIC_IP" ]; then
-              echo "Error: Invalid IP format in ec2_ip.txt."
-              echo "Raw IP from file: $RAW_IP"
-              exit 1
-            fi
-
-            echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
-            echo "Extracted EC2 Public IP: $EC2_PUBLIC_IP"
-          else
+          if [ ! -f ec2_ip.txt ]; then
             echo "Error: ec2_ip.txt not found."
             exit 1
           fi
+          
+          # Leer la dirección IP del archivo
+          RAW_IP=$(head -n 1 ec2_ip.txt | tr -d '\r\n')
+          
+          # Validar que es una dirección IP válida
+          CLEANED_IP=$(echo "$RAW_IP" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+          if [ -z "$CLEANED_IP" ]; then
+            echo "Error: Invalid IP format in ec2_ip.txt."
+            echo "Raw IP from file: $RAW_IP"
+            exit 1
+          fi
+          
+          # Exportar la dirección IP como variable de entorno
+          echo "EC2_PUBLIC_IP=$CLEANED_IP" >> $GITHUB_ENV
+          echo "Extracted EC2 Public IP: $CLEANED_IP"
+
+      - name: Debug GITHUB_ENV
+        run: cat $GITHUB_ENV
 
       # - name: Get EC2 Public IP
       #   id: get_ec2_ip
