Test Get EC2 Public IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -79,18 +79,17 @@ jobs:
       # - name: Debug EC2 Public IP
       #   run: echo "Extracted EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}"
         
-      - name: Configure EC2 and Deploy Container
+      - name: Get EC2 Public IP
+        id: get_ec2_ip
         run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
-          chmod 600 ~/.ssh/deploy_key
-
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key $INSTANCE_USER@$EC2_PUBLIC_IP "
-            sudo docker stop \$(sudo docker ps -q) || true &&
-            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
-          "
-        env:
-          EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}
+          RAW_OUTPUT=$(terraform output -raw web_server_public_ip || true)
+          EC2_PUBLIC_IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+          if [ -z "$EC2_PUBLIC_IP" ]; then
+            echo "Error: Could not extract a valid IP address."
+            exit 1
+          fi
+          echo "Extracted EC2 Public IP: $EC2_PUBLIC_IP"
+          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
 
       # # 13. Depurar Dirección Pública del EC2 Exportada
       # - name: Debug EC2 Public IP
